version: "2"

services:
  workspace:
    image: dung13890/laravel-env
    restart: always
    volumes:
      - ./:/var/www/app
    expose:
      - "9000"
    tty: true
    links:
     - mysql
  mysql:
    restart: always
    image: mysql
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
